package de.matthiasennen.transcript.ui.main

private val whisperLanguageNamesGerman = mapOf(
    "af" to "Afrikaans",
    "am" to "Amharisch",
    "ar" to "Arabisch",
    "as" to "Assamesisch",
    "az" to "Aserbaidschanisch",
    "ba" to "Baschkirisch",
    "be" to "Belarussisch",
    "bg" to "Bulgarisch",
    "bn" to "Bengalisch",
    "bo" to "Tibetisch",
    "br" to "Bretonisch",
    "bs" to "Bosnisch",
    "ca" to "Katalanisch",
    "cs" to "Tschechisch",
    "cy" to "Walisisch",
    "da" to "Dänisch",
    "de" to "Deutsch",
    "el" to "Griechisch",
    "en" to "Englisch",
    "es" to "Spanisch",
    "et" to "Estnisch",
    "eu" to "Baskisch",
    "fa" to "Persisch",
    "fi" to "Finnisch",
    "fo" to "Färöisch",
    "fr" to "Französisch",
    "gl" to "Galicisch",
    "gu" to "Gujarati",
    "ha" to "Hausa",
    "haw" to "Hawaiianisch",
    "he" to "Hebräisch",
    "hi" to "Hindi",
    "hr" to "Kroatisch",
    "ht" to "Haitianisches Kreolisch",
    "hu" to "Ungarisch",
    "hy" to "Armenisch",
    "id" to "Indonesisch",
    "is" to "Isländisch",
    "it" to "Italienisch",
    "ja" to "Japanisch",
    "jw" to "Javanisch",
    "ka" to "Georgisch",
    "kk" to "Kasachisch",
    "km" to "Khmer",
    "kn" to "Kannada",
    "ko" to "Koreanisch",
    "la" to "Latein",
    "lb" to "Luxemburgisch",
    "ln" to "Lingala",
    "lo" to "Laotisch",
    "lt" to "Litauisch",
    "lv" to "Lettisch",
    "mg" to "Malagasy",
    "mi" to "Māori",
    "mk" to "Mazedonisch",
    "ml" to "Malayalam",
    "mn" to "Mongolisch",
    "mr" to "Marathi",
    "ms" to "Malaiisch",
    "mt" to "Maltesisch",
    "my" to "Birmanisch",
    "ne" to "Nepali",
    "nl" to "Niederländisch",
    "nn" to "Nynorsk",
    "no" to "Norwegisch",
    "oc" to "Okzitanisch",
    "pa" to "Punjabi",
    "pl" to "Polnisch",
    "ps" to "Paschtunisch",
    "pt" to "Portugiesisch",
    "ro" to "Rumänisch",
    "ru" to "Russisch",
    "sa" to "Sanskrit",
    "sd" to "Sindhi",
    "si" to "Singhalesisch",
    "sk" to "Slowakisch",
    "sl" to "Slowenisch",
    "sn" to "Shona",
    "so" to "Somali",
    "sq" to "Albanisch",
    "sr" to "Serbisch",
    "su" to "Sundanesisch",
    "sv" to "Schwedisch",
    "sw" to "Swahili",
    "ta" to "Tamil",
    "te" to "Telugu",
    "tg" to "Tadschikisch",
    "th" to "Thailändisch",
    "tk" to "Turkmenisch",
    "tl" to "Tagalog",
    "tr" to "Türkisch",
    "tt" to "Tatarisch",
    "uk" to "Ukrainisch",
    "ur" to "Urdu",
    "uz" to "Usbekisch",
    "vi" to "Vietnamesisch",
    "yi" to "Jiddisch",
    "yo" to "Yoruba",
    "yue" to "Kantonesisch",
    "zh" to "Chinesisch"
)

internal fun whisperLanguageDisplayName(code: String): String {
    val normalizedCode = code.trim().lowercase()
    if (normalizedCode.isEmpty()) return "Unbekannt"
    return whisperLanguageNamesGerman[normalizedCode] ?: "Unbekannt ($normalizedCode)"
}
